# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1255, 875)
        MainWindow.setMinimumSize(QtCore.QSize(1255, 875))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fav/blpr_fav_logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_button.sizePolicy().hasHeightForWidth())
        self.clear_button.setSizePolicy(sizePolicy)
        self.clear_button.setMinimumSize(QtCore.QSize(250, 60))
        self.clear_button.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.clear_button.setFont(font)
        self.clear_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_button.setMouseTracking(True)
        self.clear_button.setStyleSheet("QPushButton{\n"
"border:1px solid #7a7a7a;\n"
"background:white;\n"
"}\n"
"QPushButton:hover{\n"
"border:1px solid black;\n"
"background:black;\n"
"color:white;\n"
"}\n"
"QPushButton:pressed{\n"
"border:1px solid white;\n"
"background:black;\n"
"color:#f0f0f0;\n"
"}")
        self.clear_button.setObjectName("clear_button")
        self.gridLayout.addWidget(self.clear_button, 4, 2, 1, 1)
        self.load_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.load_label.setFont(font)
        self.load_label.setAlignment(QtCore.Qt.AlignCenter)
        self.load_label.setObjectName("load_label")
        self.gridLayout.addWidget(self.load_label, 1, 0, 1, 2)
        self.export_data_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_data_button.sizePolicy().hasHeightForWidth())
        self.export_data_button.setSizePolicy(sizePolicy)
        self.export_data_button.setMinimumSize(QtCore.QSize(250, 60))
        self.export_data_button.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.export_data_button.setFont(font)
        self.export_data_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.export_data_button.setMouseTracking(True)
        self.export_data_button.setStyleSheet("QPushButton{\n"
"border:1px solid #7a7a7a;\n"
"background:white;\n"
"}\n"
"QPushButton:hover{\n"
"border:1px solid black;\n"
"background:black;\n"
"color:white;\n"
"}\n"
"QPushButton:pressed{\n"
"border:1px solid white;\n"
"background:black;\n"
"color:#f0f0f0;\n"
"}")
        self.export_data_button.setObjectName("export_data_button")
        self.gridLayout.addWidget(self.export_data_button, 3, 2, 1, 1)
        self.history_legacy = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_legacy.sizePolicy().hasHeightForWidth())
        self.history_legacy.setSizePolicy(sizePolicy)
        self.history_legacy.setMinimumSize(QtCore.QSize(250, 657))
        self.history_legacy.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.history_legacy.setFont(font)
        self.history_legacy.setMouseTracking(False)
        self.history_legacy.setStyleSheet("border:1px solid #7a7a7a;")
        self.history_legacy.setReadOnly(True)
        self.history_legacy.setPlaceholderText("Здесь будут отображаться отсканированные номерные знаки")
        self.history_legacy.setObjectName("history_legacy")
        self.gridLayout.addWidget(self.history_legacy, 2, 2, 1, 1)
        self.recognize_num_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recognize_num_button.sizePolicy().hasHeightForWidth())
        self.recognize_num_button.setSizePolicy(sizePolicy)
        self.recognize_num_button.setMinimumSize(QtCore.QSize(981, 125))
        self.recognize_num_button.setMaximumSize(QtCore.QSize(16777215, 140))
        self.recognize_num_button.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.recognize_num_button.setFont(font)
        self.recognize_num_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recognize_num_button.setMouseTracking(True)
        self.recognize_num_button.setStyleSheet("QPushButton{\n"
"border:1px solid #7a7a7a;\n"
"background:white;\n"
"}\n"
"QPushButton:hover{\n"
"border:1px solid black;\n"
"background:black;\n"
"color:white;\n"
"}\n"
"QPushButton:pressed{\n"
"border:1px solid white;\n"
"background:black;\n"
"color:#f0f0f0;\n"
"}")
        self.recognize_num_button.setObjectName("recognize_num_button")
        self.gridLayout.addWidget(self.recognize_num_button, 3, 0, 2, 2)
        self.history_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.history_label.setFont(font)
        self.history_label.setAlignment(QtCore.Qt.AlignCenter)
        self.history_label.setObjectName("history_label")
        self.gridLayout.addWidget(self.history_label, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 3)
        self.image_place = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_place.sizePolicy().hasHeightForWidth())
        self.image_place.setSizePolicy(sizePolicy)
        self.image_place.setAutoFillBackground(False)
        self.image_place.setStyleSheet("border:1px solid #7a7a7a;\n"
"background:white;")
        self.image_place.setText("")
        self.image_place.setScaledContents(True)
        self.image_place.setAlignment(QtCore.Qt.AlignCenter)
        self.image_place.setOpenExternalLinks(False)
        self.image_place.setObjectName("image_place")
        self.gridLayout.addWidget(self.image_place, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Basic License Plate Recognizer"))
        self.clear_button.setText(_translate("MainWindow", "Очистить"))
        self.load_label.setText(_translate("MainWindow", "Загруженное изображение автомобиля:"))
        self.export_data_button.setText(_translate("MainWindow", "Экспорт данных"))
        self.history_legacy.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Century Gothic\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.recognize_num_button.setText(_translate("MainWindow", "Распознать номер"))
        self.history_label.setText(_translate("MainWindow", "История распознаваний:"))
